services:

  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__ContainerConnection=Server=db;Database=TodoDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer

    volumes:
      - sqldata:/var/opt/mssql/data
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
volumes:
  sqldata: